### PR TITLE
Update to 14.2.4

### LINKED ISSUE #5: @conda-forge-admin, please rerender
### Additional comment:

14.2.4 was released.

### PR DESCRIPTION
**Pull request by mathbunnyru**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes: https://github.com/conda-forge/reproc-feedstock/pull/6
Closes: https://github.com/conda-forge/reproc-feedstock/issues/5

### CODE REVIEW

**Comment by mathbunnyru** [comment]
https://github.com/conda-forge/reproc-feedstock/issues/5

**Comment by mathbunnyru** [comment]
@conda-forge-admin, please rerender

**Comment by mathbunnyru** [comment]
@wolfv may I ask you to take a look and merge, please?

**Comment by wolfv** [comment]
Thanks!

**Pull request merged**
